name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: login
      env:
       DOCKER_USER: ${{ secrets.DOCKER_USER }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u ${{ secrets.DOCKER_USER }} -p  {{ secrets.$DOCKER_PASSWORD }}
    - name: build image 
      run: docker build . --file Dockerfile --tag reactapp:$(date +%s)
    - name: docker push
      run: docker push ${{ secrets.DOCKER_USER }}/githubreact
  
