name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix :
        node-version: [15.x]
    steps:
    - name: checkout
      uses: actions/checkout@v1
    - name: insatll and build 
      run: npm install &&  npm run build
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p  {{ secrets.$DOCKERHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: build image 
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/githubreact:v1
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubreact:v1
  
