name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
#      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p  {{ secrets.$DOCKERHUB_TOKEN }}
    - name: build image 
      run: docker build . --file Dockerfile --tag reactapp:$(date +%s)
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/githubreact
  
